name: Manual Build & Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to use for build & deploy'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64
          tags: |
            syl1709/petclinic:latest
            syl1709/petclinic:${{ github.event.inputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: leo-asdf/petclinic-argocd
          ref: main

      - name: Update values-deployment.yaml
        run: |
          pwd
          sed -i "s/deployImageTag:.*/deployImageTag: ${{ github.event.inputs.version }}/" petclinc-app/values-deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add values-deployment.yaml
          git commit -m "Update deployImageTag to ${{ github.event.inputs.version }}"
          git push
